apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-backend
  labels:
    app: hospital-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-backend
  template:
    metadata:
      labels:
        app: hospital-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/eswarvempali/hospital-management-backend:latest
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/bookmydoctordb?useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
