apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: example.com # replace with your domain
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: hospital-frontend
                port:
                  number: 80
